### ISSUE TITLE
Definition of meta is gone?

### ISSUE THREAD

**Issue by tischi** [BioImageTools/ome-zarr-image-analysis-nextflow#6]
@BioinfoTongLI I cannot find the definition of the `meta` anymore: https://github.com/BioImageTools/ome-zarr-image-analysis-nextflow/blob/develop/main.nf

**Comment by BioinfoTongLI** [comment]
oh, sorry. I 've removed it from the `main.nf` and put them into the `params-file`. It's basically just a `dict`
https://github.com/BioImageTools/ome-zarr-image-analysis-nextflow/blob/develop/data/input_params.yaml#L3-L6

**Comment by tischi** [comment]
Ah, it's only there in the `develop` branch....right?

**Comment by BioinfoTongLI** [comment]
yea... I will PR the dev into main now
